name: bacLIFE_environment_BAKTA
channels:
    - conda-forge
    - bioconda
    - r
    - defaults
dependencies:
    - blast
    - phylophlan
    - snakemake
    - scipy
    - biopython
    - diamond
    - bakta=1.12.0
    - bioawk
    - perl-bioperl
    - mmseqs2
    - hmmer==3.4
    - mcl
    - bioconductor-biostrings
    - r-proc
    - r-readr
    - r-stringr
    - r-upsetr  
    - r-dplyr
    - r-base
    - r-splitstackshape
    - r-reshape2
    - r-tidyverse
    - r-plyr
    - r-gtools
    - r-data.table
    - r-randomforest
    - r-dbi
    - r-rsqlite
    - scikit-learn

